use_frameworks!

platform :ios, '13.0'

target 'UserActionOne_Example' do
  pod 'UserActionOne', :path => '../'
#  pod 'Alamofire'
pod 'ProgressHUD'
  target 'UserActionOne_Tests' do
    inherit! :search_paths

    
  end
end
